export const formPages = [
{"title": "Personal Informations", "header": "Who are you?","inputFields":[], },
{"title": "Personal Informations", "header": "Where do you currently live?","inputFields":[], },
{"title": "Personal Informations", "header": "And your phone number?","inputFields":[], },
{"title": "Personal Informations", "header": "Email and Website","inputFields":[], },
{"title": "Personal Informations", "header": "Whats your current (main) Job?","inputFields":[], },
{"title": "Personal Informations", "header": "Do you have to pay church tax?","inputFields":[], },
{"title": "Your Finanzamt", "header": "Enter the name of your tax office here","inputFields":[], },
{"title": "Personal Informations", "header": "Whats your german ID (\"Identifikationsnummer\")","inputFields":[], },
{"title": "Personal Informations", "header": "Are you married?","inputFields":[], },
{"title": "Personal Informations", "header": "Since when?","inputFields":[], },
{"title": "Your Partner", "header": "Who is your Partner?","inputFields":[], },
{"title": "Your Partner", "header": "Do you live together?","inputFields":[], },
{"title": "Your Partner", "header": "Where do they live?","inputFields":[], },
{"title": "Your Partner", "header": "What is there current job?","inputFields":[], },
{"title": "Your Partner", "header": "Do they have a german tax-id?","inputFields":[], },
{"title": "Your Partner", "header": "Do they have to pay church tax?","inputFields":[], },
{"title": "Your Partner", "header": "Have you been married before?","inputFields":[], },
{"title": "Your Partner", "header": "Fill this only If you have been married before and dont live together now.","inputFields":[], },
{"title": "Your new Profession", "header": "So what tell us do you wanna do?","inputFields":[], },
{"title": "Your Bank Account", "header": "Please share your bank details with us.","inputFields":[], },
{"title": "SEPA", "header": "Do you want to sign a SEPA Mandat? This allows the tax office to automatically collect your taxes.\n","inputFields":[], },
{"title": "Tax Consultant", "header": "Do you have a Tax Consultant?","inputFields":[], },
{"title": "Tax Consultant", "header": "What is the name of your tax consulating office?","inputFields":[], },
{"title": "Tax Consultant", "header": "And whats the name of your consultant?","inputFields":[], },
{"title": "Tax Consultant", "header": "Where are they located?","inputFields":[], },
{"title": "Tax Consultant", "header": "Do you have there contact details?","inputFields":[], },
{"title": "Document Recipient", "header": "Do you recieve all your tax relevant documents or is someone else handling it?","inputFields":[], },
{"title": "Document Recipient", "header": "Whats the name of the recipient?...","inputFields":[], },
{"title": "Document Recipient", "header": "...and their adress?","inputFields":[], },
{"title": "Document Recipient", "header": "Can you share their contact details?","inputFields":[], },
{"title": "Migration Date", "header": "When did you move here?","inputFields":[], },
{"title": "Not So Personal Informations", "header": "Where did you live before?","inputFields":[], },
{"title": "Not So Personal Informations", "header": "Did you or your partner had a tax_id in germany before?","inputFields":[], },
{"title": "Not So Personal Informations", "header": "Fill this only if you or your partner lived in germany during the last three years","inputFields":[], },
{"title": "Workplace", "header": "Do you want to registrer your business on your home address or somewhere else? All tax related documents will be send to this address.","inputFields":[], },
{"title": "Workplace", "header": "What is the name of the company where you want your documents delivered to?","inputFields":[], },
{"title": "Workplace", "header": "Where is your workplace?","inputFields":[], },
{"title": "Workplace", "header": "Would you share there contact details?","inputFields":[], },
{"title": "Your new Profession", "header": "When will you start your new freelance profession?","inputFields":[], },
{"title": "Exptected Income", "header": "Your expected income for the first year?","inputFields":[], },
{"title": "Exptected Income", "header": "Your expected income for the second year?","inputFields":[], },
{"title": "Exptected Income", "header": "The expected amount of \"special\" expenses for the second year?","inputFields":[], },
{"title": "Exptected Income", "header": "The expected amount of \"special\" expenses for the second year?","inputFields":[], },
{"title": "Exptected Income", "header": "The Sum of your expected netto income","inputFields":[], },
{"title": "Exptected Income", "header": "Your Partners expected income for the first year?","inputFields":[], },
{"title": "Exptected Income", "header": "Your Partners expected income for the second year?","inputFields":[], },
{"title": "Exptected Income", "header": "The expected amount of \"special\" expenses of your Partner for the first year?","inputFields":[], },
{"title": "Exptected Income", "header": "The expected amount of \"special\" expenses of your Partner for the second year?","inputFields":[], },
{"title": "Exptected Income", "header": "Tell us if you will have any other form of earnings determination","inputFields":[], },
{"title": "Personal Informations", "header": "Enter your Tax ID here","inputFields":[], },
{"title": "Small Business Rul", "header": "Do you want to use the \"Kleinunternehmer Regel\"?","inputFields":[], },
{"title": "Unique Tax Law", "header": "Tell us if you have any tax exemption","inputFields":[], },
{"title": "Unique Tax Law", "header": "Tell us if you have a different tax rate","inputFields":[], },
{"title": "Sales Tax ID", "header": "Write down your sales tax Id if you had one in germany before","inputFields":[], },
{"title": "Last Page", "header": "Write down the City and Date","inputFields":[], },
];